version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/symfony:rw,cached
    environment:
      - SYMFONY_ENV=dev
    networks:
      - symfony
    depends_on:
      - db

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/symfony:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - symfony
    depends_on:
      - php

  # PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - symfony

networks:
  symfony:

volumes:
  db_data: